public class CoffeeMachine implements ICoffeeMachine {

    public Drink brewCoffee(Integer amount, Integer strength) {
        return null;
    }

    public Drink boilWater(Integer amount) {
        return null;
    }

    public void rinseMachine() {
    }

    public void addWater(Integer amount) {
    }

    public Integer getDrinksServed() {
        return null;
    }

    public Integer getWaterLevel() {
        return null;
    }
    
}